---
- name: Copy file remotely to server
  hosts: all
  become: true
  tasks:
     - name: Copy file to remote server
       copy:
          src: files/index.html
          dest: /var/www/html
          owner: root
          group: root
          mode: '0644'
